#ifndef _FEAL_COMMON_WIN_H
#define _FEAL_COMMON_WIN_H

#ifndef _FEAL_H
#error "Please include feal.h and not the other internal Feal header files, to avoid include errors."
#endif

#include "winsock2.h"
#include "w2tcpip.h"

namespace feal
{
    
typedef enum
{
    S_OK = 0,
    S_E2BIG = E2BIG,
    S_EACCES = EACCES,
    S_EADDRINUSE = EADDRINUSE,
    S_EADDRNOTAVAIL = EADDRNOTAVAIL,
    S_EAFNOSUPPORT = EAFNOSUPPORT,
    S_EAGAIN = EAGAIN,
    S_EALREADY = EALREADY,
    S_EBUSY = EBUSY,
    S_ECANCELED = ECANCELED,
    S_ECHILD = ECHILD,
    S_ECONNABORTED = ECONNABORTED,
    S_ECONNREFUSED = ECONNREFUSED,
    S_ECONNRESET = ECONNRESET,
    S_EDEADLK = EDEADLK,
    S_EDESTADDRREQ = EDESTADDRREQ,
    S_EDOM = EDOM,
    S_EDQUOT = EDQUOT,
    S_EEXIST = EEXIST,
    S_EFAULT = EFAULT,
    S_EFBIG = EFBIG,
    S_EHOSTDOWN = EHOSTDOWN,
    S_EHOSTUNREACH = EHOSTUNREACH,
    S_EIDRM = EIDRM,
    S_EILSEQ = EILSEQ,
    S_EINPROGRESS = EINPROGRESS,
    S_EINTR = EINTR,
    S_EINVAL = EINVAL,
    S_EIO = EIO,
    S_EISCONN = EISCONN,
    S_EISDIR = EISDIR,
    S_ELOOP = ELOOP,
    S_EMFILE = EMFILE,
    S_EMLINK = EMLINK,
    S_EMSGSIZE = EMSGSIZE,
    S_EMULTIHOP = EMULTIHOP,
    S_ENAMETOOLONG = ENAMETOOLONG,
    S_ENETDOWN = ENETDOWN,
    S_ENETRESET = ENETRESET,
    S_ENETUNREACH = ENETUNREACH,
    S_ENFILE = ENFILE,
    S_ENOBUFS = ENOBUFS,
    S_ENODATA = ENODATA,
    S_ENODEV = ENODEV,
    S_ENOENT = ENOENT,
    S_ENOEXEC = ENOEXEC,
    S_ENOLCK = ENOLCK,
    S_ENOLINK = ENOLINK,
    S_ENOMEM = ENOMEM,
    S_ENOMSG = ENOMSG,
    S_ENOPROTOOPT = ENOPROTOOPT,
    S_ENOSPC = ENOSPC,
    S_ENOSR = ENOSR,
    S_ENOSTR = ENOSTR,
    S_ENOSYS = ENOSYS,
    S_ENOTBLK = ENOTBLK,
    S_ENOTCONN = ENOTCONN,
    S_ENOTDIR = ENOTDIR,
    S_ENOTEMPTY = ENOTEMPTY,
    S_ENOTRECOVERABLE = ENOTRECOVERABLE,
    S_ENOTSOCK = ENOTSOCK,
    S_ENOTSUP = ENOTSUP,
    S_ENOTTY = ENOTTY,
    S_ENXIO = ENXIO,
    S_EOPNOTSUPP = EOPNOTSUPP,
    S_EOVERFLOW = EOVERFLOW,
    S_EOWNERDEAD = EOWNERDEAD,
    S_EPERM = EPERM,
    S_EPFNOSUPPORT = EPFNOSUPPORT,
    S_EPIPE = EPIPE,
    S_EPROTO = EPROTO,
    S_EPROTONOSUPPORT = EPROTONOSUPPORT,
    S_EPROTOTYPE = EPROTOTYPE,
    S_ERANGE = ERANGE,
    S_EREMOTE = EREMOTE,
    S_EROFS = EROFS,
    S_ESHUTDOWN = ESHUTDOWN,
    S_ESPIPE = ESPIPE,
    S_ESOCKTNOSUPPORT = ESOCKTNOSUPPORT,
    S_ESRCH = ESRCH,
    S_ESTALE = ESTALE,
    S_ETIME = ETIME,
    S_ETIMEDOUT = ETIMEDOUT,
    S_ETOOMANYREFS = ETOOMANYREFS,
    S_ETXTBSY = ETXTBSY,
    S_EUSERS = EUSERS,
    S_EWOULDBLOCK = EWOULDBLOCK,
    S_EXDEV = EXDEV
} errenum;


typedef int socket_t;


typedef uint32_t EventId_t;
typedef uint32_t ActorId_t;
typedef enum {INET=AF_INET, INET6=AF_INET6, UNIX=AF_UNIX} family_t;

typedef struct {
    enum {INET=AF_INET, INET6=AF_INET6} family;
    uint16_t port;
    char addr[INET6_ADDRSTRLEN];
} ipaddr;

}


#endif // _FEAL_COMMON_WIN_H
